PracticaWeb/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.contrib.auth import views as v
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from rest_framework import routers
from forkilla import views

router = routers.DefaultRouter()
router.register(r'restaurants', views.RestaurantViewSet, base_name="Restaurant")

listOfAddresses = ['http://localhost:8000', "localhost"]

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^forkilla/', include('forkilla.urls')),
    url(r'', include('forkilla.urls')),
    url(r'^accounts/login/$', v.LoginView.as_view(), name='login'),
    url(r'^accounts/logout/$', v.LogoutView.as_view(), {'next_page': '/forkilla'}, name='logout'),
    url(r'^api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('users/', views.UserList.as_view()),
    path('users/<int:pk>/', views.UserDetail.as_view()),
    url(r'^comparator$', views.comparator, {'ips': listOfAddresses}),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

forkilla/urls.py
from django.conf.urls import url
from django.conf.urls import include
from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^restaurants/$', views.restaurants, name='restaurants'),
    url(r'^restaurants/(?P<city>.*)/$', views.restaurants, name='restaurants'),
    url(r'^restaurant/(?P<restaurant_number>.*)/$', views.details, name='details'),
    url(r'^restaurants/(?P<city>.*)/(?P<category>.*)$', views.restaurants, name='restaurants'),
    url(r'^reservation/$', views.reservation, name='reservation'),
    url(r'^checkout/$', views.checkout, name='checkout'),
    url(r'^restaurant/(?P<restaurant_number>.*)/comment$', views.add_comment, name='add_comment'),
    url(r'^restaurant/(?P<restaurant_number>.*)/review$', views.review, name='review'),
    url(r'^search/$', views.search_restaurant, name='search'),
    url(r'^register/$', views.register, name='register'),
    url(r'^delete/(?P<id>.*)$', views.deleteReservation, name='deleteReservation'),
    url(r'^reservationlist/$', views.reservationlist, name='reservationlist'),
]

forkilla/models.py
from django.db import models
from datetime import datetime
from django.core.validators import MinValueValidator

from django.contrib.auth.models import User

from django_comments.moderation import CommentModerator, moderator

from pygments.lexers import get_lexer_by_name
from pygments.formatters.html import HtmlFormatter
from pygments import highlight

from .global_vars import ROLES


#########################################################
#   Every time this class is changed follow these steps:#
#                                                       #
#   1. Change your models (in models.py).               #
#   2. Run python manage.py makemigrations to create    #
#      migrations for those changes                     #   
#   3. Run python manage.py migrate to apply those      #
#      changes to the database.                         #
#########################################################

# To load fixture data: python manage.py loaddata <fixturename>

# Create your models here.
class Restaurant(models.Model):
    CATEGORIES = (
        ("Rice", "Rice"),
        ("Fusi", "Fusion"),
        ("BBQ", "Barbecue"),
        ("Chin", "Chinese"),
        ("Medi","Mediterranean"),
        ("Crep","Creperie"),
        ("Hind","Hindu"),
        ("Japa","Japanese"),
        ("Ital","Italian"),
        ("Mexi","Mexican"),
        ("Peru", "Peruvian"),
        ("Russ","Russian"),
        ("Turk","Turkish"),
        ("Basq","Basque"),
        ("Vegy", "Vegetarian"),
        ("Afri","African"),
        ("Egyp","Egyptian"),
        ("Grek","Greek")
    )
    _d_categories = dict(CATEGORIES)

    restaurant_number = models.CharField(max_length=8, unique=True)
    name = models.CharField(max_length=50)
    menu_description = models.TextField()
    price_average = models.DecimalField(max_digits=5, decimal_places=2)
    is_promot = models.BooleanField()
    rate = models.DecimalField(max_digits=3, decimal_places=1)
    address = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    country = models.CharField(max_length=50)
    featured_photo = models.ImageField(upload_to ='images/', default='images/1.jpeg')
    category = models.CharField(max_length=5, choices=CATEGORIES)
    restaurant_capacity = models.PositiveIntegerField()

    def get_human_category(self):
        return self._d_categories[self.category]

    def __str__(self):
        return ('[**Promoted**]' if self.is_promot else '') + "[" + self.category + "] " \
                "[" + self.restaurant_number + "] " + self.name + " - " + self.menu_description + " (" + str(self.rate) + ")" \
                ": " + str(self.price_average) + u" €"
                
class Reservation(models.Model):
    SLOTS = (
        ("morning_first", "12h00"),
        ("morning_second", "13h00"),
        ("morning_third", "14h00"),
        ("morning_fourth", "15h00"),
        ("evening_first", "20h00"),
        ("evening_second", "21h00"),
        ("evening_third", "22h00"),
    )
    _d_slots = dict(SLOTS)
    id = models.AutoField(primary_key=True)
    restaurant = models.ForeignKey(Restaurant, on_delete=models.PROTECT)
    day = models.DateField(default=datetime.now)
    time_slot = models.CharField(max_length=15, choices=SLOTS)
    num_people = models.PositiveIntegerField(default=1, validators=[MinValueValidator(1)])
    user = models.CharField(max_length=200, default="Anonymous User")

    def get_human_slot(self):
        return self._d_slots[self.time_slot]
        
    def __str__(self):
        return "Reservation at: " + self.restaurant.name + " on " + str(self.day) + " for " + str(self.num_people) + " people, on " + str(self.time_slot)
        
class ViewedRestaurants(models.Model):
    id_vr = models.AutoField(primary_key=True)
    restaurant = models.ManyToManyField(Restaurant)
    
class RestaurantInsertDate(models.Model):
    viewedrestaurants = models.ForeignKey(ViewedRestaurants, on_delete=models.CASCADE)
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-date_added']
        
class ReviewRestaurant(models.Model):
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE, null=True, related_name='reviews')
    user = models.CharField(max_length=200, default="Anonymous User")
    stars = models.PositiveIntegerField(default=0)
    
class Comment(models.Model):
    the_restaurant = models.ForeignKey('Restaurant', on_delete=models.CASCADE, null=False, related_name='comments')
    user = models.CharField(max_length=200, default="Anonymous User")
    posted_date = models.DateTimeField(auto_now_add=True)
    content = models.TextField()
    approved_comment = models.BooleanField(default=False)
    
    def approved(self):
        self.approved_comment = True
        self.save()
        
    def __str__(self):
        return self.content
        
class Snippet(models.Model):
    owner = models.ForeignKey('auth.User', related_name='snippets', on_delete=models.CASCADE)
    highlighted = models.TextField()
    
    def save(self, *args, **kwargs):
        lexer = get_lexer_by_name(self.language)
        linenos = 'table' if self.linenos else False
        options = {'title': self.title} if self.title else {}
        formatter = HtmlFormatter(style=self.style, linenos=linenos,
                                  full=True, **options)
        self.highlighted = highlight(self.code, lexer, formatter)
        super(Snippet, self).save(*args, **kwargs)
        
class UserRole(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    role = models.CharField(max_length=15, choices=ROLES)

forkilla/forms.py
from django import forms

from .models import Reservation, Comment, ReviewRestaurant

class ReservationForm(forms.ModelForm):

    class Meta:
        model = Reservation
        fields = ["day", "time_slot", "num_people"]
        
class CommentsForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["content", ]
        
class RateForm(forms.ModelForm):
    class Meta:
        model = ReviewRestaurant
        fields = ('stars', )

forkilla/templates/forkilla/add_comment.html
{% extends 'forkilla/base.html' %}

{% block title %}Add comment{% endblock %}

{% block content %}
<div class="login">
    <div class="form">
        
        <h1>Add new comments</h1>
        
        {% if form.errors %}
            <p class="error">Sorry, that's not a valid comment</p>
        {% endif %}

        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Submit</button>
        </form>
    </div><!-- Closing div login -->
</div><!-- Closing div form -->
{% endblock %}

forkilla/templates/forkilla/base.html
<!DOCTYPE html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Forkilla - {% block title %}{% endblock %}</title>
        <meta name="author" content="Vitor Carvalho and Ivet Aymerich">
        <meta name="copyright" content="2019 Registered">
        <meta name="description" content="Under construction">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        {% load static %}
        <!-- Favicon -->
        <link rel="shortcut icon" href="{% static 'img/logo.png' %}">

        <!-- CSS STYLE -->
        <link rel="stylesheet" href="{% static 'css/main.css' %}">

        {% block css %}
        {% endblock %}
        <!-- THE ICON FONTS -->

        <!-- GOOGLE FONTS -->
        <link href="https://fonts.googleapis.com/css?family=Grand+Hotel|Lobster+Two|Pacifico|Roboto" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Bad+Script" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Alex+Brush" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Farsan" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
        
        <!-- Font Awesome -->
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
        
        <!-- JQuery -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="{% static "js/header.js" %}"></script>
        
        <!-- BootStrap CSS 
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        
         BootStrap JS
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
 -->
        <!-- Main js -->

    </head>

    <body onresize="myFunction()">
        {% include 'forkilla/header.html' %}
        
        {% block content %}
        
        {% endblock %}

        {% block scripts %}
        {% endblock %}
        <script>
            function myFunction() {
                var windowWidth = $(window).width();
                var slideCount = $('#slider li').length;
                var slides = windowWidth * slideCount;
                $('#slider').css("width", slides)
            }
        </script>
    </body>
</html>

forkilla/templates/forkilla/checkout.html
{% extends 'forkilla/base.html' %}

{% block title %} Checkout Reservation {% endblock %}

{% block css %}
<link rel="stylesheet" href="/static/css/login.css">
{% endblock %}

{% block content %}

<div class="login_section">
    <div class="login">
        <div class="form">
            <h2>Thank you for your Reservation</h2>
            {{reserva}}
        </div><!-- Closing div login -->
    </div><!-- Closing div form -->
</div>

{% endblock %}

forkilla/templates/forkilla/comparator.html
{% extends "forkilla/base.html" %}
{% load staticfiles %}

{% block title %} Comparator {% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static "css/comparator.css" %}">
{% endblock %}


{% block content %}
    <div class="page_body">
        <div class="center">
            <h3>
                Search your list of restaurants
            </h3> 
        </div>
        
        <div class="form_section center">
            <ul>
                <li>
                    <select type="number" name="max_price" id="category" placeholder="Category">
                        <option value="all" selected>All categories</option>
                        {% for category in categories %}
                            <option value="{{ category.0 }}">{{ category.1 }}</option>
                        {% endfor %}
                    </select>
                </li>
                
                <li>
                    <select type="text" name="city" id="city" placeholder="City">
                        <option value="all" selected>All cities</option>
                        {% for city in cities %}
                            <option value="{{ city }}">{{ city }}</option>
                        {% endfor %}
                    </select>
                </li>
                
                <li>
                    <input type="number" name="max_price" id="max_price" class="form-control" step="any" placeholder="Price">
                </li>
                
                <li>
                    <button type="button" class="compare">Compare</button>
                </li>
            </ul>
        </div><!-- Closing div form_section -->
        
        <div class="results">
            <div class="error_container">
                
            </div><!-- clsoing div error_container -->
            
            
            <div class="body_mostViewed_restaurants" style="width:100% !important;">
                
            </div>
        </div><!-- clsoing div results -->
    </div>
{% endblock %}

{% block scripts %}
    <script>
        $('.compare').on('click', function() {
            
            var ips = {{ ips | safe }};
            var restaurants = $('.body_mostViewed_restaurants');
            restaurants.empty();
            var params = '?';
            var restaurants_dict = [];
            
            const cat = $('#category');
            if (cat.val() !== "all") {
                params += 'category=' + cat.val();
            }
            
            const city = $('#city');
            if (city.val() !== 'all') {
                params.length > 2 ? params += '&city=' + city.val() : params += 'city=' + city.val();
            }
            
            const m_price = $('#max_price');
            if (m_price.val() !== '') {
                params.length > 2 ? params += '&price=' + m_price.val() : params += 'price=' + m_price.val();
            }
                
            $.ajax({
                url: ips[0] + '/api/restaurants/' + params,
                type: 'GET', //Allowed without auth
                dataType: 'json',
                error: function () {
                   console.log('ERROR with ip ---' + ips[i]);
                   $('.error_container').append('<span class="error"> There has been an error with this filters on the following api:' + ikea_ips[i] + '</span>')
                },
                success: function (data) {
                    data.results.forEach(function(restaurant) {
                        
                        card = '<div class="restaurant_card">' +
                                    '<img src="' + restaurant.featured_photo + '" ' + 'alt="not found"/>' +
                                    '<h3>' + restaurant.name + '</h3>' +
                                    '<p>' +
                                        restaurant.price_average + '$' +
                                    '</p>' +
                                    '<div>' +
                                        '<p>' +
                                            restaurant.menu_description +
                                        '</p>' +
                                        
                                        '<p> Rate: ' +
                                            restaurant.rate + ' ' +
                                            'Address: ' +
                                            restaurant.address + ' ' +
                                            restaurant.city + ' ' +
                                            restaurant.country + ' ' +
                                        '</p>' +
                                        
                                        '<br>' +
                                        
                                        '<p>' +
                                            restaurant.restaurant_capacity +
                                        '</p>' +
                                    '</div>' +
                                '</div>';
                        
                        /*restaurants_dict.push(card);*/
                        restaurants.append(card);
                        
                    });
                }
            });
            
            /*restaurants_dict.sort(function(restaurant1, restaurant2) {
                return restaurant1.price - restaurant2.price;
            });
            
            console.log(restaurants_dict);
            
            for (var i = 0; i < restaurants_dict.length; i++) {
                console.log("1");
            }
            
            console.log(restaurants_dict);*/
        });
    </script>
{% endblock %}

forkilla/templates/forkilla/deleteReservation.html
{% extends 'forkilla/base.html' %}

{% block title %} Deleting reservation {% endblock %}

{% block content %}


{% endblock %}

forkilla/templates/forkilla/details.html
{% extends 'forkilla/base.html' %}

{% block title %}
    {% if name %}
        {{name}}
    {% else %}
        not found
    {% endif %}
{% endblock %}

{% block content %}
<link rel="stylesheet" href="/static/css/details.css">
<div class="container">
    <div class="restaurant_name center">
        <h1 class="title">Welcome</h1>
        <h3>{{name}}</h3>
        <hr id="asterisk" data-content="*">
        <p>
            Restaurant specilized in {{category}}
        </p>
        
        <p>
            <!-- the Restaurant rating -->
            <span class="hint-star star">
                {% if stars == 0 %}
                    <i class="fa fa-star-half-o" aria-hidden="true"></i>
                    <i class="fa fa-star-half-o" aria-hidden="true"></i>
                    <i class="fa fa-star-half-o" aria-hidden="true"></i>
                    <i class="fa fa-star-half-o" aria-hidden="true"></i>
                    <i class="fa fa-star-o" aria-hidden="true"></i>
                {% elif stars == 1 %}
                    <i class="fa fa-star" aria-hidden="true"></i>
                    <i class="fa fa-star-half-o" aria-hidden="true"></i>
                    <i class="fa fa-star-half-o" aria-hidden="true"></i>
                    <i class="fa fa-star-half-o" aria-hidden="true"></i>
                    <i class="fa fa-star-o" aria-hidden="true"></i>
                {% elif stars == 2 %}
                    <i class="fa fa-star" aria-hidden="true"></i>
                    <i class="fa fa-star" aria-hidden="true"></i>
                    <i class="fa fa-star-half-o" aria-hidden="true"></i>
                    <i class="fa fa-star-half-o" aria-hidden="true"></i>
                    <i class="fa fa-star-o" aria-hidden="true"></i>
                {% elif stars == 3 %}
                    <i class="fa fa-star" aria-hidden="true"></i>
                    <i class="fa fa-star" aria-hidden="true"></i>
                    <i class="fa fa-star" aria-hidden="true"></i>
                    <i class="fa fa-star-half-o" aria-hidden="true"></i>
                    <i class="fa fa-star-o" aria-hidden="true"></i>
                {% elif stars == 4 %}
                    <i class="fa fa-star" aria-hidden="true"></i>
                    <i class="fa fa-star" aria-hidden="true"></i>
                    <i class="fa fa-star" aria-hidden="true"></i>
                    <i class="fa fa-star" aria-hidden="true"></i>
                    <i class="fa fa-star-o" aria-hidden="true"></i>
                {% else %}
                    <i class="fa fa-star" aria-hidden="true"></i>
                    <i class="fa fa-star" aria-hidden="true"></i>
                    <i class="fa fa-star" aria-hidden="true"></i>
                    <i class="fa fa-star" aria-hidden="true"></i>
                    <i class="fa fa-star" aria-hidden="true"></i>
                    
                {% endif %}
            </span>
        </p>
    </div><!-- Closing div card restaurant_name -->
    
    <div class="card">
        <div class="card_text_div">
            <div class="card_title">
                <h1 class="title">Discover</h1>
            </div><!-- Closing div card_title -->
            
            <div class="card_sub_tittle">
                <h3>*</h3>
            </div><!-- Closing div card_sub_tittle -->
            
            <div class="card_text">
                <p>
                    {{menu_description}}
                    Price average: 
                    {{price_average}}
                    Rate: 
                    {{rate}}
                    Address: 
                    {{address}}
                    {{city}} 
                    {{country}}
                </p>
                
                <form action="{% url 'reservation' %}" method="get">
                    {% csrf_token %}
                    <button type="submit" name="reservation" value="{{restaurant_number}}" class="reserva"> 
                        Reserva 
                    </button>
                </form>
                
                {% if user.is_authenticated %}
                    <div class="rate_Section center">
                        <h3>Rate this Restaurant:</h3>
                        <form action="{% url 'review' restaurant.restaurant_number %}" method="POST">
                            {% csrf_token %}
                            <p class="clasificacion">
                                <input id="radio1" type="radio" name="estrellas" value="5">
                                <label for="radio1">★</label>
                                <input id="radio2" type="radio" name="estrellas" value="4">
                                <label for="radio2">★</label>
                                <input id="radio3" type="radio" name="estrellas" value="3">
                                <label for="radio3">★</label>
                                <input id="radio4" type="radio" name="estrellas" value="2">
                                <label for="radio4">★</label>
                                <input id="radio5" type="radio" name="estrellas" value="1">
                                <label for="radio5">★</label>
                            </p>
                            
                            <input  type="submit" value="Rate"/>
                        </form>
                    </div><!-- Closing div rate_Section -->
                {% endif %}
                
            </div><!-- Closing div card_text -->
        </div><!-- Closing div card_text_div -->
        
        <div class="card_image">
            {% if restaurant.featured_photo %}
                <img src={{ restaurant.featured_photo.url }} alt="not found"/>
            {% endif %}
        </div><!-- Closing div card_image -->
    </div><!-- Closing div card -->
    
    
    <div class="comment_section">
        <hr />
        
        <div class="new_comment">
            {% if user.is_authenticated %}
                <h1>Leave a Comment in this Restaurant</h1>
                
                {% if form.errors %}
                    <p class="error">Sorry, that's not a valid comment</p>
                {% endif %}

                <form method="POST" action="{% url 'add_comment' restaurant.restaurant_number %}">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input class="reserva" type="submit" value="Comment"/>
                </form>
            {% endif %}
        </div>
        
        
        <hr />
        <ul class="timeline">
        {% for comment in restaurant.comments.all %}
            <li>
                <p class="timeline-date">{{ comment.posted_date }}</p>
                <div class="timeline-content">
                    <h3>{{ comment.user }}</h3>
                    <p>{{ comment.content }}</p>
                </div>
            </li>
        {% endfor %}
        </ul>
    </div>
    
    {% include 'forkilla/mostViewedRestaurants.html' %}
</div><!-- Closing div container -->
{% endblock %}

forkilla/templates/forkilla/error.html
{% extends 'forkilla/base.html' %}

{% block title %} Error fiding path {% endblock %}

{% block content %}


{% endblock %}

forkilla/templates/forkilla/header.html
<header>
    {% include 'forkilla/navbar.html' %}
    
    <div class="header_logo">
        <h1 >
            <a class="logo" href="{% url 'index' %}">Forkilla</a>
        </h1>
    </div><!-- Closing div header_logo -->

    <div class="search">
        <form action="/search/" method="GET">
            <input type="text" name="q" value="{{query|escape}}" placeholder="Search Restaurant"/>
            <input type="submit" value="search" />
        </form>
    </div>

    <div class="login-section">
        {% if user.is_authenticated %}
            <div class="user_ui">
                <div class="user_menu_toggle">
                    <div class="profile_img">
                        
                    </div><!-- Closing div profile_img -->
                    
                    <span class="simple_arrow fa fa-chevron-up"></span>
                </div><!-- Closing div user_menu_toggle -->
                
                <!-- USER MENU -->
                
                <div class="user_menu">
                    <div class="user_info">
                        <div class="profile_img">
                            
                        </div><!-- Closing div profile_img -->
                        
                        <h4>{{ user.get_username }}</h4>
                        
                        <br />
                        
                        <a class="" href="{% url 'reservationlist' %}">Tus Reservas</a>
                        
                        <hr />
                        
                        <a class="fa fa-power-off" href="/accounts/logout/?next=/forkilla">Logout</a>
                    </div>
                </div><!-- Closing div user_menu -->
            </div><!--  Closing div user_ui -->
        {% else %}
            <div class="user_options">
                <ul>
                    <li>
                        <a class="" href="/accounts/login/?next=/forkilla">Login</a>
                    </li>
                    <li>
                        <a class="" href="{% url 'register' %}">Register</a>
                    </li>
                </ul>
            </div>
        {% endif %}
    </div>
</header>

forkilla/templates/forkilla/index.html
{% extends 'forkilla/base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
<link rel="stylesheet" href="/static/css/index.css">
<div class="container">
    <div class="prommoted_restaurants_section">
        <div class="body_promoted_restaurants">
            <div class="slide-window">
                <ul class="slides" id="slider">
                    {% for restaurant in restaurants %}
                    <li class="slide color-0" style="background-image:url({{ restaurant.featured_photo.url }});">
                        
                        <h2>{{ restaurant.name }}</h2>
                    
                        <a class="button" href="{% url 'details' restaurant.restaurant_number %}">View More</a>
                    
                    </li>
                    {% endfor %}
                </ul>
                
                <span class="nav fa fa-chevron-left fa-3x left"></span>
                <span class="nav fa fa-chevron-right fa-3x right"></span>
            </div><!-- Closing div slide-window -->
        </div><!-- Closing div body_promoted_restaurants -->
    </div><!-- Closing div prommoted_restaurants_section -->
    
    
    {% include 'forkilla/mostViewedRestaurants.html' %}
</div><!-- Closing div container -->


{% endblock %}

forkilla/templates/forkilla/mostViewedRestaurants.html
<section>
    <div class="center">
        <h2>
            Your last viewed Restaurants
        </h2> 
    </div>
    
    <br>
    <form action="{% url 'reservation' %}" method="post">
        {% csrf_token %}
        <div class="body_mostViewed_restaurants">
            {% for restaurant in viewedrestaurants.restaurantinsertdate_set.all|slice:"5"%}
                <div class="restaurant_card">
                    {% if restaurant.restaurant.featured_photo %}
                        <img src="{{ restaurant.restaurant.featured_photo.url }}" alt="not found"/>
                    {% endif %}                
                    <div>
                        <h3>{{restaurant.restaurant.name}}</h3>
                        
                        <a href="{% url 'details' restaurant.restaurant.restaurant_number%}"> {{restaurant.restaurant.name}} </a> : {{restaurant.restaurant.menu_description}}

                        <br>
                        
                        <p>
                            {{restaurant.restaurant.menu_description}}
                        </p>
                        
                        <!--<form action="{% url 'reservation' %}" method="get">
                            {% csrf_token %}
                            <button type="submit" name="reservation" value="{{restaurant.restaurant_number}}" class="reserva"> 
                                Reserva 
                            </button>
                        </form>-->
                        
                        <a href="{% url 'details' restaurant.restaurant.restaurant_number%}"> View More </a>
                    </div>
                </div><!-- Closing div restaurant_card -->
            {% endfor %}
        </div><!-- Closing div body_mostViewed_restaurants -->
    </form>
</section>